name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch: {}
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 'tty.sdf.org'
          username: 'nutandevjoshi'
          password: '780sOaeURq0w'
          source: "README.md"
          target: "/sdf/udd/n/nutandevjoshi"
          debug: "true"

      - name: executing remote ssh commands using password via appleboy repo
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 'tty.sdf.org'
          username: 'nutandevjoshi'
          password: '780sOaeURq0w'
          script: |
            echo "whoami-->"
            whoami
